# Generated by Django 2.2.5 on 2020-02-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0002_auto_20200206_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.DeleteModel(
            name='Username',
        ),
    ]
