# Generated by Django 2.2.5 on 2020-02-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='username',
            table='Username',
        ),
    ]
