# Generated by Django 2.2.5 on 2020-02-10 00:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0003_auto_20200206_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 10, 0, 57, 50, 162224, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
