# Generated by Django 2.2.5 on 2020-02-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0004_user_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='animal_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=50)),
                ('foodImg', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'animal_list',
            },
        ),
    ]
